DROP TABLE IF EXISTS posts;

DROP TABLE IF EXISTS usuario;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE usuario (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nome TEXT NOT NULL,
    idade date NOT NULL,
    email TEXT NOT NULL,
    login TEXT NOT NULL,
    senha TEXT NOT NULL,
    comentario TEXT NOT NULL
);